### ISSUE TITLE
Cannot build the library

### ISSUE THREAD

**Issue by rachelray1** [OperatorFoundation/CanaryLinux#1]
I am trying to build the project and it throws errors like 

<img width="1420" alt="Screenshot 2023-07-11 at 1 46 19 PM" src="https://github.com/OperatorFoundation/CanaryLinux/assets/74740574/68db341f-1025-4dbe-819c-62b3e06d9c3d">

Please let us know how to proceed next

**Comment by bragelbytes** [comment]
Hello. With our latest push, this issue has been resolved. We will also let you know when a more stable release is available as well.

**Comment by rachelray1** [comment]
Hello, thank you, build issue is resolved. But I cannot run the command. Could you please help me with the setup process? 
After running the command: ```sudo Canary```: it shows ```Canary: command not found```

**Comment by bragelbytes** [comment]
Hello, please try running it with the path to the executable. 
sudo `<path-to-canarylinux-executable>` `<path-to-config-directory>`
example: sudo .build/x86_64-unknown-linux-gnu/debug/CanaryLinux `<path-to-config-directory>`

**Comment by rachelray1** [comment]
Hi, it got resolved with: 

~/CanaryLinux/.build/x86_64-unknown-linux-gnu/debug# ./CanaryLinux `<path-to-config-directory>`

**Comment by bragelbytes** [comment]
That's great! Thank you
